
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 343330528
 */
public class GameSettingsHistory extends javax.swing.JFrame {
    //Define methods
    
    /**
     * This method iterates through all of the previously set settings objects (game/search engine/social media) of the currently 
     * logged in user account and adds each game settings object to the game settings history combo box
     * 
     * @param settingsArray  Instance variable of the current User object storing all of their previous setting configurations
     */
    private void setGameHistoryComboBox(ArrayList<BasicSettings> settingsArray) {
        //Clear all items in game settings history combo box before adding updated set of settings objects as items
        gameHistoryComboBox.removeAllItems(); //Clear game settings history

                
        //Iterate through each BasicSettings object in the array list of BasicSettings
        for (BasicSettings settings : settingsArray) {
            //Check if the BasicSettings object's instance type is GameSettings so that it can downcast
            if (settings instanceof GameSettings)
                //Downcast BasicSettings object to GameSettings object, add to game settings history combo box
                gameHistoryComboBox.addItem((GameSettings) settings);
        } //End for loop iterating through array list of settings objects
    }
    
    
    /**
     * Creates new form GameSettingsHistory
     */
    public GameSettingsHistory() {
        initComponents();

        //Set top label to display logged-in account's username
        usernameLabel.setText(HomeScreen.currentUser.getUsername() + "'s Game Settings History");
        
        //Set items in game history settings combo box
        setGameHistoryComboBox(HomeScreen.currentUser.getSettings());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        difficultyLabel = new javax.swing.JLabel();
        subtitlesLabel = new javax.swing.JLabel();
        resolutionLabel = new javax.swing.JLabel();
        notificationsLabel = new javax.swing.JLabel();
        controlLabel = new javax.swing.JLabel();
        locationLabel = new javax.swing.JLabel();
        graphicsLabel = new javax.swing.JLabel();
        microphoneLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        gameHistoryComboBox = new javax.swing.JComboBox<>();
        returnButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        difficultyLabel.setText("Difficulty Level:");

        subtitlesLabel.setText("Subtitles On:");

        resolutionLabel.setText("Screen Resolution:");

        notificationsLabel.setText("Notifications On:");

        controlLabel.setText("Control Scheme:");

        locationLabel.setText("Location On:");

        graphicsLabel.setText("Graphics Quality:");

        microphoneLabel.setText("Microphone On:");

        usernameLabel.setText("User's Game Settings History");

        gameHistoryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameHistoryComboBoxActionPerformed(evt);
            }
        });

        returnButton.setText("Return");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(usernameLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(microphoneLabel)
                            .addComponent(locationLabel)
                            .addComponent(notificationsLabel)
                            .addComponent(difficultyLabel)
                            .addComponent(subtitlesLabel)
                            .addComponent(resolutionLabel)
                            .addComponent(controlLabel)
                            .addComponent(graphicsLabel))))
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(gameHistoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(returnButton)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(usernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(gameHistoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(notificationsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(locationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(microphoneLabel)
                .addGap(28, 28, 28)
                .addComponent(difficultyLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subtitlesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resolutionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(controlLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(graphicsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(returnButton)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gameHistoryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameHistoryComboBoxActionPerformed
        //Retrieve the current selected item (GameSettings object) from the combo box when the user clicks on an item
        GameSettings selectedGameSettingsVersion = (GameSettings) gameHistoryComboBox.getSelectedItem();
        
        if (selectedGameSettingsVersion != null) {
            //Display the selected GameSettings object's notifications attribute in the corresponding text field
            notificationsLabel.setText("Notifications: " + selectedGameSettingsVersion.getAllowNotifications());
            //Display the selected GameSettings object's location sharing attribute in the corresponding text field
            locationLabel.setText("Location: " + selectedGameSettingsVersion.getLocationSharing());
            //Display the selected GameSettings object's microphone access attribute in the corresponding text field
            microphoneLabel.setText("Microphone: " + selectedGameSettingsVersion.getMicrophoneAccess());

            //Display the selected GameSettings object's difficulty level attribute in the corresponding text field
            difficultyLabel.setText("Difficulty Level: " + selectedGameSettingsVersion.getDifficultyLevel());
            //Display the selected GameSettings object's subtitles enabled attribute in the corresponding text field
            subtitlesLabel.setText("Subtitles: " + selectedGameSettingsVersion.getSubtitlesEnabled());
            //Display the selected GameSettings object's screen resolution attribute in the corresponding text field
            resolutionLabel.setText("Screen Resolution: " + selectedGameSettingsVersion.getScreenResolution());
            //Display the selected GameSettings object's control scheme attribute in the corresponding text field
            controlLabel.setText("Control Scheme: " + selectedGameSettingsVersion.getControlScheme());
            //Display the selected GameSettings object's graphics quality attribute in the corresponding text field
            graphicsLabel.setText("Graphics Quality: " + selectedGameSettingsVersion.getGraphicsQuality());
        }
    }//GEN-LAST:event_gameHistoryComboBoxActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        //Return to settings screen after user finishes looking at previous game settings
        new SettingsScreen().setVisible(true); //Show settings screen frame
        this.setVisible(false); //Hide current frame (game settings history)
    }//GEN-LAST:event_returnButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameSettingsHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameSettingsHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameSettingsHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameSettingsHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameSettingsHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel controlLabel;
    private javax.swing.JLabel difficultyLabel;
    private javax.swing.JComboBox<GameSettings> gameHistoryComboBox;
    private javax.swing.JLabel graphicsLabel;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JLabel microphoneLabel;
    private javax.swing.JLabel notificationsLabel;
    private javax.swing.JLabel resolutionLabel;
    private javax.swing.JButton returnButton;
    private javax.swing.JLabel subtitlesLabel;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
