/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * Home Screen of Settings Simulator that displays button options for the user to edit friends, change password, view settings,
 * or logout
 * 
 * @author   Kimi Ong
 * @version  1.0
 * @since    2025-04-29
 */
public class HomeScreen extends javax.swing.JFrame {
    //Global variables
    public static User currentUser; //Current user account that is being displayed and interacted with
    
    
    /**
     * Creates new form HomeScreen
     */
    public HomeScreen() {
        initComponents();
        
        //Set top label to display logged-in account's username
        usernameLabel.setText(currentUser.getUsername() + "'s Account");
        //Set email label to display logged-in account's email
        emailLabel.setText("Email: " + currentUser.getEmail());
        //Check if user entered their birthday when they created an account (value is not default 0)
        if (currentUser.getBirthday().getMonth() != 0)
            //Set birthday label to display logged-in account's birthday
            birthdayLabel.setText("Birthday: " + currentUser.getBirthday());
        //If user did not enter their birthday
        else
            //Set birthday label to tell user they did not provide a birthday
            birthdayLabel.setText("Birthday: Not provided");
         //Check if user entered their phone number when they created an account (value is not default 000)
        if (!(currentUser.getPhoneNumber().equals("000")))
            //Set phone number label to display logged-in account's phone number
            phoneNumberLabel.setText("Phone Number: " + currentUser.getPhoneNumber());
        //If user did not enter their phone number
        else
            //Set phone number label to tell user they did not provide a phone number
            phoneNumberLabel.setText("Phone Number: Not provided");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameLabel = new javax.swing.JLabel();
        friendsButton = new javax.swing.JButton();
        passwordButton = new javax.swing.JButton();
        settingsButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        emailLabel = new javax.swing.JLabel();
        birthdayLabel = new javax.swing.JLabel();
        phoneNumberLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usernameLabel.setFont(new java.awt.Font("Gurmukhi MT", 0, 18)); // NOI18N
        usernameLabel.setText("User's Account");

        friendsButton.setFont(new java.awt.Font("Hiragino Sans", 0, 12)); // NOI18N
        friendsButton.setText("Friends");
        friendsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                friendsButtonActionPerformed(evt);
            }
        });

        passwordButton.setFont(new java.awt.Font("Hiragino Sans", 0, 12)); // NOI18N
        passwordButton.setText("Change Password");
        passwordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordButtonActionPerformed(evt);
            }
        });

        settingsButton.setFont(new java.awt.Font("Hiragino Sans", 0, 12)); // NOI18N
        settingsButton.setText("Settings");
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });

        logoutButton.setFont(new java.awt.Font("Hiragino Sans", 0, 12)); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        emailLabel.setFont(new java.awt.Font("Hiragino Sans", 0, 12)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(0, 0, 153));
        emailLabel.setText("Email: ");

        birthdayLabel.setFont(new java.awt.Font("Hiragino Sans", 0, 12)); // NOI18N
        birthdayLabel.setForeground(new java.awt.Color(0, 0, 153));
        birthdayLabel.setText("Birthday:");

        phoneNumberLabel.setFont(new java.awt.Font("Hiragino Sans", 0, 12)); // NOI18N
        phoneNumberLabel.setForeground(new java.awt.Color(0, 0, 153));
        phoneNumberLabel.setText("Phone Number: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(140, 140, 140)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(friendsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(passwordButton)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(99, 99, 99)
                            .addComponent(usernameLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(birthdayLabel)
                            .addComponent(emailLabel)
                            .addComponent(phoneNumberLabel))))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(usernameLabel)
                .addGap(30, 30, 30)
                .addComponent(emailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(birthdayLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoneNumberLabel)
                .addGap(18, 18, 18)
                .addComponent(friendsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(settingsButton)
                .addGap(30, 30, 30)
                .addComponent(logoutButton)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void friendsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_friendsButtonActionPerformed
        //Go to edit friends screen if user clicks on "Friends" button
        new EditFriends().setVisible(true); //Show edit friends screen frame
        this.setVisible(false); //Hide current frame (home screen)
    }//GEN-LAST:event_friendsButtonActionPerformed

    private void passwordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordButtonActionPerformed
        //Go to change password screen if user clicks on "Change Password" button
        new ChangePassword().setVisible(true); //Show change password screen frame
        this.setVisible(false); //Hide current frame (home screen)
    }//GEN-LAST:event_passwordButtonActionPerformed

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        //Go to home settings screen if user clicks on "Settings" button
        new SettingsScreen().setVisible(true); //Show settings screen frame
        this.setVisible(false); //Hide current frame (home screen)
    }//GEN-LAST:event_settingsButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        //Go to login screen if user clicks on "Logout" button
        new Login().setVisible(true); //Show login screen frame
        this.setVisible(false); //Hide current frame (home screen)
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel birthdayLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JButton friendsButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton passwordButton;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JButton settingsButton;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
