/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 343330528
 */
public class SettingsScreen extends javax.swing.JFrame {

    /**
     * Creates new form SettingsScreen
     */
    public SettingsScreen() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        gameButton = new javax.swing.JButton();
        gameHistoryButton = new javax.swing.JButton();
        searchEngineButton = new javax.swing.JButton();
        searchEngineHistoryButton = new javax.swing.JButton();
        socialMediaButton = new javax.swing.JButton();
        socialMediaHistoryButton = new javax.swing.JButton();
        explanationButton = new javax.swing.JButton();
        returnButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("User's Settings");

        jLabel2.setText("Game Settings:");

        jLabel3.setText("Search Engine Settings:");

        jLabel4.setText("Social Media Settings:");

        gameButton.setText("View/Edit");
        gameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameButtonActionPerformed(evt);
            }
        });

        gameHistoryButton.setText("History");
        gameHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameHistoryButtonActionPerformed(evt);
            }
        });

        searchEngineButton.setText("View/Edit");
        searchEngineButton.setToolTipText("");
        searchEngineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEngineButtonActionPerformed(evt);
            }
        });

        searchEngineHistoryButton.setText("History");
        searchEngineHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEngineHistoryButtonActionPerformed(evt);
            }
        });

        socialMediaButton.setText("View/Edit");
        socialMediaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                socialMediaButtonActionPerformed(evt);
            }
        });

        socialMediaHistoryButton.setText("History");
        socialMediaHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                socialMediaHistoryButtonActionPerformed(evt);
            }
        });

        explanationButton.setText("View Current Settings Explanation");
        explanationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                explanationButtonActionPerformed(evt);
            }
        });

        returnButton.setText("Return to Main Screen");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(68, 68, 68)
                                .addComponent(gameButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(gameHistoryButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(socialMediaButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(socialMediaHistoryButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(searchEngineButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(searchEngineHistoryButton))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(returnButton)
                            .addComponent(explanationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(gameButton)
                    .addComponent(gameHistoryButton))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(searchEngineButton)
                    .addComponent(searchEngineHistoryButton))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(socialMediaButton)
                    .addComponent(socialMediaHistoryButton))
                .addGap(27, 27, 27)
                .addComponent(explanationButton)
                .addGap(31, 31, 31)
                .addComponent(returnButton)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameButtonActionPerformed
        new UserGameSettings().setVisible(true); //Show game settings frame
        this.setVisible(false); //Hide current frame (settings screen)
    }//GEN-LAST:event_gameButtonActionPerformed

    private void searchEngineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEngineButtonActionPerformed
        new UserSearchEngineSettings().setVisible(true); //Show search engine settings frame
        this.setVisible(false); //Hide current frame (settings screen)
    }//GEN-LAST:event_searchEngineButtonActionPerformed

    private void socialMediaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_socialMediaButtonActionPerformed
        new UserSocialMediaSettings().setVisible(true); //Show social media settings frame
        this.setVisible(false); //Hide current frame (settings screen)
    }//GEN-LAST:event_socialMediaButtonActionPerformed

    private void gameHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameHistoryButtonActionPerformed
        new GameSettingsHistory().setVisible(true); //Show game settings history frame
        this.setVisible(false); //Hide current frame (settings screen)
    }//GEN-LAST:event_gameHistoryButtonActionPerformed

    private void searchEngineHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEngineHistoryButtonActionPerformed
        new SearchEngineSettingsHistory().setVisible(true); //Show search engine settings history frame
        this.setVisible(false); //Hide current frame (settings screen)
    }//GEN-LAST:event_searchEngineHistoryButtonActionPerformed

    private void socialMediaHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_socialMediaHistoryButtonActionPerformed
        new SocialMediaSettingsHistory().setVisible(true); //Show social media settings history frame
        this.setVisible(false); //Hide current frame (settings screen)
    }//GEN-LAST:event_socialMediaHistoryButtonActionPerformed

    private void explanationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explanationButtonActionPerformed
        new DisplayExplanations().setVisible(true); //Show display all settings explanations frame
        this.setVisible(false); //Hide current frame (settings screen)
    }//GEN-LAST:event_explanationButtonActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        //Return to home screen after user finishes looking at settings
        new HomeScreen().setVisible(true); //Show home screen frame
        this.setVisible(false); //Hide current frame (settings screen)
    }//GEN-LAST:event_returnButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SettingsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SettingsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SettingsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettingsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SettingsScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton explanationButton;
    private javax.swing.JButton gameButton;
    private javax.swing.JButton gameHistoryButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton returnButton;
    private javax.swing.JButton searchEngineButton;
    private javax.swing.JButton searchEngineHistoryButton;
    private javax.swing.JButton socialMediaButton;
    private javax.swing.JButton socialMediaHistoryButton;
    // End of variables declaration//GEN-END:variables
}
