import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 343330528
 */
public class SocialMediaSettingsHistory extends javax.swing.JFrame {
    //Define methods
    
    /**
     * This method iterates through all of the previously set settings objects (game/search engine/social media) of the currently 
     * logged in user account and adds each social media settings object to the social media settings history combo box
     * 
     * @param settingsArray  Instance variable of the current User object storing all of their previous setting configurations
     */
    private void setSocialMediaHistoryComboBox(ArrayList<BasicSettings> settingsArray) {
        //Clear all items in social media settings history combo box before adding updated set of settings objects as items
        socialMediaHistoryComboBox.removeAllItems(); //Clear social media settings history

                
        //Iterate through each BasicSettings object in the array list of BasicSettings
        for (BasicSettings settings : settingsArray) {
            //Check if the BasicSettings object's instance type is SocialMediaSettings so that it can downcast
            if (settings instanceof SocialMediaSettings)
                //Downcast BasicSettings object to SocialMediaSettings object, add to social media settings history combo box
                socialMediaHistoryComboBox.addItem((SocialMediaSettings) settings);
        } //End for loop iterating through array list of settings objects
    }
    
    
    /**
     * Creates new form SocialMediaSettingsHistory
     */
    public SocialMediaSettingsHistory() {
        initComponents();
        
        //Set top label to display logged-in account's username
        usernameLabel.setText(HomeScreen.currentUser.getUsername() + "'s Social Media Settings History");
        
        //Set items in social media history settings combo box
        setSocialMediaHistoryComboBox(HomeScreen.currentUser.getSettings());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameLabel = new javax.swing.JLabel();
        notificationsLabel = new javax.swing.JLabel();
        socialMediaHistoryComboBox = new javax.swing.JComboBox<>();
        locationLabel = new javax.swing.JLabel();
        microphoneLabel = new javax.swing.JLabel();
        birthdayPrivacyLabel = new javax.swing.JLabel();
        emailPrivacyLabel = new javax.swing.JLabel();
        phoneNumberPrivacyLabel = new javax.swing.JLabel();
        mentionsPrivacyLabel = new javax.swing.JLabel();
        messagesPrivacyLabel = new javax.swing.JLabel();
        storiesPrivacyLabel = new javax.swing.JLabel();
        returnButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usernameLabel.setText("User's Social Media Settings History");

        notificationsLabel.setText("Notifications On:");

        socialMediaHistoryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                socialMediaHistoryComboBoxActionPerformed(evt);
            }
        });

        locationLabel.setText("Location On:");

        microphoneLabel.setText("Microphone On:");

        birthdayPrivacyLabel.setText("Public Birthday:");

        emailPrivacyLabel.setText("Public Email:");

        phoneNumberPrivacyLabel.setText("Public Phone Number:");

        mentionsPrivacyLabel.setText("Public Mentions:");

        messagesPrivacyLabel.setText("Public Messages:");

        storiesPrivacyLabel.setText("Public Stories:");

        returnButton.setText("Return");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(messagesPrivacyLabel)
                            .addComponent(mentionsPrivacyLabel)
                            .addComponent(phoneNumberPrivacyLabel)
                            .addComponent(emailPrivacyLabel)
                            .addComponent(birthdayPrivacyLabel)
                            .addComponent(microphoneLabel)
                            .addComponent(locationLabel)
                            .addComponent(notificationsLabel)
                            .addComponent(socialMediaHistoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(storiesPrivacyLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                                .addComponent(returnButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(usernameLabel)))
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(usernameLabel)
                .addGap(18, 18, 18)
                .addComponent(socialMediaHistoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(notificationsLabel)
                        .addGap(18, 18, 18)
                        .addComponent(locationLabel)
                        .addGap(18, 18, 18)
                        .addComponent(microphoneLabel)
                        .addGap(40, 40, 40)
                        .addComponent(birthdayPrivacyLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(emailPrivacyLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(phoneNumberPrivacyLabel)
                        .addGap(12, 12, 12)
                        .addComponent(mentionsPrivacyLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(messagesPrivacyLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(storiesPrivacyLabel)
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(returnButton)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void socialMediaHistoryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_socialMediaHistoryComboBoxActionPerformed
        //Retrieve the current selected item (SocialMediaSettings object) from the combo box when the user clicks on an item
        SocialMediaSettings selectedSocialMediaSettingsVersion = (SocialMediaSettings) socialMediaHistoryComboBox.getSelectedItem();
        
        //Display the selected SocialMediaSettings object's notifications attribute in the corresponding text field
        notificationsLabel.setText("Notifications: " + selectedSocialMediaSettingsVersion.getAllowNotifications());
        //Display the selected SocialMediaSettings object's location sharing attribute in the corresponding text field
        locationLabel.setText("Location: " + selectedSocialMediaSettingsVersion.getLocationSharing());
        //Display the selected SocialMediaSettings object's microphone access attribute in the corresponding text field
        microphoneLabel.setText("Microphone: " + selectedSocialMediaSettingsVersion.getMicrophoneAccess());
        
        //Display the selected SocialMediaSettings object's birthday privacy attribute in the corresponding text field
        birthdayPrivacyLabel.setText("Birthday Privacy: " + selectedSocialMediaSettingsVersion.getBirthdayPrivacy());
        //Display the selected SocialMediaSettings object's email privacy attribute in the corresponding text field
        emailPrivacyLabel.setText("Email Privacy: " + selectedSocialMediaSettingsVersion.getEmailPrivacy());
        //Display the selected SocialMediaSettings object's phone number privacy attribute in the corresponding text field
        phoneNumberPrivacyLabel.setText("Phone Number Privacy: " + selectedSocialMediaSettingsVersion.getPhoneNumberPrivacy());
        //Display the selected SocialMediaSettings object's mentions privacy attribute in the corresponding text field
        mentionsPrivacyLabel.setText("Mentions Privacy: " + selectedSocialMediaSettingsVersion.getMentionsPrivacy());
        //Display the selected SocialMediaSettings object's messages privacy attribute in the corresponding text field
        messagesPrivacyLabel.setText("Messages Privacy: " + selectedSocialMediaSettingsVersion.getMessagesPrivacy());
        //Display the selected SocialMediaSettings object's stories privacy attribute in the corresponding text field
        storiesPrivacyLabel.setText("Stories Privacy: " + selectedSocialMediaSettingsVersion.getStoriesPrivacy());
    }//GEN-LAST:event_socialMediaHistoryComboBoxActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        //Return to settings screen after user finishes looking at previous social media settings
        new SettingsScreen().setVisible(true); //Show settings screen frame
        this.setVisible(false); //Hide current frame (social media settings history)
    }//GEN-LAST:event_returnButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SocialMediaSettingsHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SocialMediaSettingsHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SocialMediaSettingsHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SocialMediaSettingsHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SocialMediaSettingsHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel birthdayPrivacyLabel;
    private javax.swing.JLabel emailPrivacyLabel;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JLabel mentionsPrivacyLabel;
    private javax.swing.JLabel messagesPrivacyLabel;
    private javax.swing.JLabel microphoneLabel;
    private javax.swing.JLabel notificationsLabel;
    private javax.swing.JLabel phoneNumberPrivacyLabel;
    private javax.swing.JButton returnButton;
    private javax.swing.JComboBox<SocialMediaSettings> socialMediaHistoryComboBox;
    private javax.swing.JLabel storiesPrivacyLabel;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
