/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * Game Settings screen of Settings Simulator that displays the currently logged in account's game settings and allows the user
 * to edit them
 * 
 * @author   Kimi Ong
 * @version  1.0
 * @since    2025-04-29
 */
public class UserGameSettings extends javax.swing.JFrame {
    //Declare Variables
    private static boolean allowNotifications; //Allow notifications from application
    private static boolean locationSharing; //Allow access to user's location
    private static boolean microphoneAccess; //Allow access to microphone
    private static String difficultyLevel; //Game's difficulty level
    private static boolean subtitlesEnabled; //Turn subtitles on or off
    private static String screenResolution; //Screen resolution
    private static String controlScheme; //How the user interacts with the game
    private static String graphicsQuality; //Graphics quality

    /**
     * Creates new form UserGameSettings
     */
    public UserGameSettings() {
        initComponents();
        
        //Set top label to display logged-in account's username
        usernameLabel.setText(HomeScreen.currentUser.getUsername() + "'s Game Settings");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        notificationsComboBox = new javax.swing.JComboBox<>();
        locationComboBox = new javax.swing.JComboBox<>();
        microphoneComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        subtitlesComboBox = new javax.swing.JComboBox<>();
        resolutionComboBox = new javax.swing.JComboBox<>();
        controlComboBox = new javax.swing.JComboBox<>();
        graphicsComboBox = new javax.swing.JComboBox<>();
        difficultyComboBox = new javax.swing.JComboBox<>();
        submitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usernameLabel.setFont(new java.awt.Font("Gurmukhi MT", 0, 18)); // NOI18N
        usernameLabel.setText("User's Game Settings");

        jLabel1.setFont(new java.awt.Font("Hiragino Sans", 0, 12)); // NOI18N
        jLabel1.setText("Difficulty Level:");

        jLabel3.setFont(new java.awt.Font("Hiragino Sans", 0, 12)); // NOI18N
        jLabel3.setText("Notifications:");

        jLabel4.setFont(new java.awt.Font("Hiragino Sans", 0, 12)); // NOI18N
        jLabel4.setText("Location:");

        jLabel5.setFont(new java.awt.Font("Hiragino Sans", 0, 12)); // NOI18N
        jLabel5.setText("Microphone:");

        notificationsComboBox.setFont(new java.awt.Font("Hiragino Sans", 0, 12)); // NOI18N
        notificationsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Allow", "Block" }));

        locationComboBox.setFont(new java.awt.Font("Hiragino Sans", 0, 12)); // NOI18N
        locationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Share", "Hide" }));

        microphoneComboBox.setFont(new java.awt.Font("Hiragino Sans", 0, 12)); // NOI18N
        microphoneComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Allow", "Block" }));

        jLabel6.setFont(new java.awt.Font("Hiragino Sans", 0, 12)); // NOI18N
        jLabel6.setText("Subtitles:");

        jLabel7.setFont(new java.awt.Font("Hiragino Sans", 0, 12)); // NOI18N
        jLabel7.setText("Screen Resolution:");

        jLabel8.setFont(new java.awt.Font("Hiragino Sans", 0, 12)); // NOI18N
        jLabel8.setText("Control Scheme:");

        jLabel9.setFont(new java.awt.Font("Hiragino Sans", 0, 12)); // NOI18N
        jLabel9.setText("Graphics Quality:");

        subtitlesComboBox.setFont(new java.awt.Font("Hiragino Sans", 0, 12)); // NOI18N
        subtitlesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "On", "Off" }));

        resolutionComboBox.setFont(new java.awt.Font("Hiragino Sans", 0, 12)); // NOI18N
        resolutionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1920x1080", "1280x720", "2560x1440" }));

        controlComboBox.setFont(new java.awt.Font("Hiragino Sans", 0, 12)); // NOI18N
        controlComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Keyboard", "Gamepad", "Custom" }));

        graphicsComboBox.setFont(new java.awt.Font("Hiragino Sans", 0, 12)); // NOI18N
        graphicsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Low", "Medium", "High" }));

        difficultyComboBox.setFont(new java.awt.Font("Hiragino Sans", 0, 12)); // NOI18N
        difficultyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Easy", "Normal", "Hard" }));

        submitButton.setFont(new java.awt.Font("Hiragino Sans", 0, 12)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(usernameLabel)
                            .addGap(127, 127, 127))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(locationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                            .addComponent(notificationsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel6))
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(difficultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(subtitlesComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel8)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(graphicsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(controlComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(resolutionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(49, 49, 49)
                                    .addComponent(microphoneComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(90, 90, 90)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(submitButton)
                        .addGap(69, 69, 69))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(usernameLabel)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(notificationsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(microphoneComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(difficultyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subtitlesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resolutionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(controlComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(graphicsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        //Check the current selected item (String) in the notifications combo box when the user submits the settings
        if (notificationsComboBox.getSelectedItem().equals("Allow"))
            //If the selected option is "Allow", set variable to true
            allowNotifications = true;
        //If selected option is not "Allow", only other option is "Block"
        else
            //If the selected option is "Block", set variable to false
            allowNotifications = false; 
        
        //Check the current selected item (String) in the location combo box when the user submits the settings
        if (locationComboBox.getSelectedItem().equals("Share"))
            //If the selected option is "Share", set variable to true
            locationSharing = true;
        //If selected option is not "Share", only other option is "Hide"
        else
            //If the selected option is "Hide", set variable to false
            locationSharing = false; 
        
        //Check the current selected item (String) in the microphone combo box when the user submits the settings
        if (microphoneComboBox.getSelectedItem().equals("Allow"))
            //If the selected option is "Allow", set variable to true
            microphoneAccess = true;
        //If selected option is not "Allow", only other option is "Block"
        else
            //If the selected option is "Block", set variable to false
            microphoneAccess = false; 
        
        
        //Check the current selected item (String) in the difficulty combo box when the user submits the settings
        if (difficultyComboBox.getSelectedItem().equals("Easy")) 
            //If the selected option is "Easy", store in variable
            difficultyLevel = "Light";
        //If selected option is "Normal", store in variable
        else if (difficultyComboBox.getSelectedItem().equals("Normal")) 
            //If the selected option is "Normal", store in variable
            difficultyLevel = "Normal"; 
        //If the selected option is not "Easy" or "Normal", only other option is "Hard"
        else
            //If the selected option is "Hard", store in variable
            difficultyLevel = "Hard";
        
        //Check the current selected item (String) in the subtitles combo box when the user submits the settings
        if (subtitlesComboBox.getSelectedItem().equals("On"))
            //If the selected option is "On", set variable to true
            subtitlesEnabled = true;
        //If selected option is not "On", only other option is "Off"
        else
            //If the selected option is "Off", set variable to false
            subtitlesEnabled = false; 
        
        //Check the current selected item (String) in the resolution combo box when the user submits the settings
        if (resolutionComboBox.getSelectedItem().equals("1920x1080")) 
            //If the selected option is "1920x1080", store in variable
            screenResolution = "1920x1080";
        //If selected option is "1280x720", store in variable
        else if (resolutionComboBox.getSelectedItem().equals("1280x720")) 
            //If the selected option is "1280x720", store in variable
            screenResolution = "1280x720"; 
        //If the selected option is not "1920x1080" or "1280x720", only other option is "2560x1440"
        else
            //If the selected option is "2560x1440", store in variable
            screenResolution = "2560x1440";
        
        //Check the current selected item (String) in the control combo box when the user submits the settings
        if (controlComboBox.getSelectedItem().equals("Gamepad")) 
            //If the selected option is "Gamepad", store in variable
            controlScheme = "Gamepad";
        //If selected option is "Keyboard", store in variable
        else if (controlComboBox.getSelectedItem().equals("Keyboard")) 
            //If the selected option is "Keyboard", store in variable
            controlScheme = "Keyboard"; 
        //If the selected option is not "Gamepad" or "Keyboard", only other option is "Custom"
        else
            //If the selected option is "Custom", store in variable
            controlScheme = "Custom";
        
        //Check the current selected item (String) in the graphics combo box when the user submits the settings
        if (graphicsComboBox.getSelectedItem().equals("Low")) 
            //If the selected option is "Low", store in variable
            graphicsQuality = "Low";
        //If selected option is "Medium", store in variable
        else if (graphicsComboBox.getSelectedItem().equals("Medium")) 
            //If the selected option is "Medium", store in variable
            graphicsQuality = "Medium"; 
        //If the selected option is not "Low" or "Medium", only other option is "High"
        else
            //If the selected option is "High", store in variable
            graphicsQuality = "High";
        
        
        //Create new instance of GameSettings class based on settings selected by the user, upcast to BasicSettings
        BasicSettings gameSettings = new GameSettings(allowNotifications, locationSharing, microphoneAccess, difficultyLevel, subtitlesEnabled, screenResolution, controlScheme, graphicsQuality);
        //Add new game settings to user object's array list of all previously set settings
        HomeScreen.currentUser.addNewSettings(gameSettings);
        
        //Set user's current game settings to the newly set game settings after downcasting
        HomeScreen.currentUser.setGameSettings((GameSettings) gameSettings);
        
        
        //Return to settings screen after user finishes editing game settings
        new SettingsScreen().setVisible(true); //Show settings screen frame
        this.setVisible(false); //Hide current frame (edit game settings)
    }//GEN-LAST:event_submitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserGameSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserGameSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserGameSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserGameSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserGameSettings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> controlComboBox;
    private javax.swing.JComboBox<String> difficultyComboBox;
    private javax.swing.JComboBox<String> graphicsComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> locationComboBox;
    private javax.swing.JComboBox<String> microphoneComboBox;
    private javax.swing.JComboBox<String> notificationsComboBox;
    private javax.swing.JComboBox<String> resolutionComboBox;
    private javax.swing.JButton submitButton;
    private javax.swing.JComboBox<String> subtitlesComboBox;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
